Repository Kernel360/KDEV3_DevLens_BE, pull requests merged in 2025-01, with the labels that each got.

#22 Setting : Ai 코드리뷰 플로우 추가
  .github/workflows/ai_code_reviewer.yml
Labels: 🌏 Deploy, ⚙ Setting

#24 Feat: S3 파일 업로드 베이스 코드 구현
  build.gradle
  src/main/java/com/seveneleven/devlens/global/config/S3Config.java
  src/main/java/com/seveneleven/devlens/global/exception/BusinessException.java
  src/main/java/com/seveneleven/devlens/global/response/APIResponse.java
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
  src/main/java/com/seveneleven/devlens/global/util/file/FileCategory.java
  src/main/java/com/seveneleven/devlens/global/util/file/FileValidator.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/S3ClientService.java
  src/main/java/com/seveneleven/devlens/global/util/file/controller/FileController.java
  src/main/java/com/seveneleven/devlens/global/util/file/dto/FileMetadataDto.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadata.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadataHistory.java
  src/main/java/com/seveneleven/devlens/global/util/file/repository/FileMetadataRepository.java
  src/main/resources/application.properties
Labels: ✨ Feature

#31 Feature/board entity update #29
  src/main/java/com/seveneleven/devlens/domain/board/dto/PostStatus.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/Answer.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/AnswerHistory.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/Comment.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/Post.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/PostHistory.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/Question.java
  src/main/java/com/seveneleven/devlens/domain/board/entity/QuestionHistory.java
Labels: ✨ Feature

#37 Update: 파일, 링크 관련 엔티티 수정
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
  src/main/java/com/seveneleven/devlens/global/util/file/FileValidator.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/S3ClientService.java
  src/main/java/com/seveneleven/devlens/global/util/file/constant/FileCategory.java
  src/main/java/com/seveneleven/devlens/global/util/file/constant/FileHistoryType.java
  src/main/java/com/seveneleven/devlens/global/util/file/constant/LinkCategory.java
  src/main/java/com/seveneleven/devlens/global/util/file/constant/LinkHistoryType.java
  src/main/java/com/seveneleven/devlens/global/util/file/controller/FileController.java
  src/main/java/com/seveneleven/devlens/global/util/file/dto/FileMetadataDto.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadata.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/FileMetadataHistory.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/Link.java
  src/main/java/com/seveneleven/devlens/global/util/file/entity/LinkHistory.java
Labels: ✨ Feature

#27 Feature/company #13
  src/main/java/com/seveneleven/devlens/domain/admin/common/EntityConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/controller/CompanyController.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/CompanyRepository.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/CompanyRequestConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/CompanyResponseConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/CompanyDto.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/PaginatedResponse.java
  src/main/java/com/seveneleven/devlens/domain/admin/exception/CompanyDuplicatedException.java
  src/main/java/com/seveneleven/devlens/domain/admin/exception/CompanyExceptionHandler.java
  src/main/java/com/seveneleven/devlens/domain/admin/service/CompanyCreateService.java
  src/main/java/com/seveneleven/devlens/domain/admin/service/CompanyReadService.java
  src/main/java/com/seveneleven/devlens/domain/member/entity/Company.java
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
Labels: ✨ Feature

#40 Update: 파일 업로드 베이스 코드 수정
  src/main/java/com/seveneleven/devlens/global/config/AuditorAwareImpl.java
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/S3ClientService.java
  src/main/java/com/seveneleven/devlens/global/util/file/controller/FileController.java
  src/main/java/com/seveneleven/devlens/global/util/file/dto/FileMetadataDto.java
  src/test/java/com/seveneleven/devlens/global/util/file/Service/FileServiceTest.java
Labels: ✨ Feature

#44 Update: Base Entity 생성자, 수정자 타입 변경
  src/main/java/com/seveneleven/devlens/global/entity/BaseEntity.java
Labels: ✨ Feature

#55 fix : api response 변경
  src/main/java/com/seveneleven/devlens/domain/project/controller/MyProjectController.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectChecklistController.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectController.java
Labels: 🐞 Fix

#45 Feature: 회사 로고 업로드 기능 추가
  src/main/java/com/seveneleven/devlens/domain/member/entity/Company.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/CompanyFileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/S3ClientService.java
  src/main/java/com/seveneleven/devlens/global/util/file/controller/CompanyFileController.java
  src/main/resources/application.properties
  src/test/java/com/seveneleven/devlens/global/util/file/Service/FileServiceTest.java
Labels: ✨ Feature

#58 Feature/member security #20
  .github/workflows/build_test.yml
  build.gradle
  src/main/java/com/seveneleven/devlens/domain/member/controller/MemberController.java
  src/main/java/com/seveneleven/devlens/domain/member/dto/MemberDto.java
  src/main/java/com/seveneleven/devlens/domain/member/dto/MemberJoinDto.java
  src/main/java/com/seveneleven/devlens/domain/member/dto/TokenDto.java
  src/main/java/com/seveneleven/devlens/domain/member/entity/Member.java
  src/main/java/com/seveneleven/devlens/domain/member/repository/MemberRepository.java
  src/main/java/com/seveneleven/devlens/domain/member/service/MemberService.java
  src/main/java/com/seveneleven/devlens/domain/member/service/MyUserDetailsService.java
  src/main/java/com/seveneleven/devlens/global/config/Annotation/AdminAuthorize.java
  src/main/java/com/seveneleven/devlens/global/config/Annotation/UserAuthorize.java
  src/main/java/com/seveneleven/devlens/global/config/JwtAccessDeniedHandler.java
  src/main/java/com/seveneleven/devlens/global/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/seveneleven/devlens/global/config/JwtFilter.java
  src/main/java/com/seveneleven/devlens/global/config/JwtSecurityConfig.java
  src/main/java/com/seveneleven/devlens/global/config/SpringSecurityConfig.java
  src/main/java/com/seveneleven/devlens/global/config/TokenProvider.java
  src/main/java/com/seveneleven/devlens/global/exception/GlobalExceptionHandler.java
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
  src/main/java/com/seveneleven/devlens/global/util/security/SecurityUtil.java
  src/main/resources/application.properties
Labels: ✨ Feature

#51 feature/apiresponse-update #50
  src/main/java/com/seveneleven/devlens/global/response/APIResponse.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
Labels: ✨ Feature

#64 Feat: 등록된 회사 로고 조회 기능 추가
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/CompanyFileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/Service/FileService.java
  src/main/java/com/seveneleven/devlens/global/util/file/controller/CompanyFileController.java
  src/main/java/com/seveneleven/devlens/global/util/file/repository/FileMetadataRepository.java
Labels: ✨ Feature

#68 Feature/admin member #49
  build.gradle
  src/main/java/com/seveneleven/devlens/domain/admin/controller/MemberMgmtController.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/MemberDto.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/MemberUpdate.java
  src/main/java/com/seveneleven/devlens/domain/admin/service/MemberMgmtService.java
  src/main/java/com/seveneleven/devlens/domain/member/MemberValidator.java
  src/main/java/com/seveneleven/devlens/domain/member/controller/MemberController.java
  src/main/java/com/seveneleven/devlens/domain/member/dto/MemberSpecification.java
  src/main/java/com/seveneleven/devlens/domain/member/dto/TokenDto.java
  src/main/java/com/seveneleven/devlens/domain/member/entity/Member.java
  src/main/java/com/seveneleven/devlens/domain/member/entity/MemberProfileHistory.java
  src/main/java/com/seveneleven/devlens/domain/member/repository/MemberRepository.java
  src/main/java/com/seveneleven/devlens/global/response/ErrorCode.java
Labels: ✨ Feature

#69 Feature : project step api #57
  src/main/java/com/seveneleven/devlens/domain/admin/db/PostProjectRequestConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/PostProjectResponseConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/ProjectHistoryConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/ProjectRequestConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/db/ProjectResponseConverter.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/GetProject.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/PostProject.java
  src/main/java/com/seveneleven/devlens/domain/admin/dto/ReadProjectHistory.java
  src/main/java/com/seveneleven/devlens/domain/member/repository/MemberRepository.java
  src/main/java/com/seveneleven/devlens/domain/member/service/MemberService.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/MyProjectController.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/MyProjectDocs.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectChecklistController.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectChecklistDocs.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectChecklistFacade.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectController.java
  src/main/java/com/seveneleven/devlens/domain/project/controller/ProjectDocs.java
  src/main/java/com/seveneleven/devlens/domain/project/dto/GetProjectDetail.java
  src/main/java/com/seveneleven/devlens/domain/project/dto/GetProjectList.java
  src/main/java/com/seveneleven/devlens/domain/project/dto/GetProjectStep.java
  src/main/java/com/seveneleven/devlens/domain/project/dto/GetStepChecklist.java
  src/main/java/com/seveneleven/devlens/domain/project/dto/PostProjectChecklist.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/CheckRequest.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/CheckResult.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/CheckResultHistory.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/Checklist.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/Project.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/ProjectHistory.java
  src/main/java/com/seveneleven/devlens/domain/project/entity/ProjectStep.java
  src/main/java/com/seveneleven/devlens/domain/project/repository/ChecklistRepository.java
  src/main/java/com/seveneleven/devlens/domain/project/repository/ProjectRepository.java
  src/main/java/com/seveneleven/devlens/domain/project/repository/ProjectStepRepository.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectChecklistService.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectChecklistServiceImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectService.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectServiceImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectStepService.java
  src/main/java/com/seveneleven/devlens/domain/project/service/ProjectStepServiceImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/checklist/ChecklistReader.java
  src/main/java/com/seveneleven/devlens/domain/project/service/checklist/ChecklistReaderImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/checklist/ChecklistStore.java
  src/main/java/com/seveneleven/devlens/domain/project/service/checklist/ChecklistStoreImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/dashboard/ProjectReader.java
  src/main/java/com/seveneleven/devlens/domain/project/service/dashboard/ProjectReaderImpl.java
  src/main/java/com/seveneleven/devlens/domain/project/service/step/StepReader.java
  src/main/java/com/seveneleven/devlens/domain/project/service/step/StepReaderImpl.java
  src/main/java/com/seveneleven/devlens/global/util/security/SecurityUtils.java
Labels: ✨ Feature

#85 CI : 깃허브 액션 멀티모듈 브랜치 추가
  .github/workflows/build_test.yml
Labels: 🌏 Deploy

#79 Feature/member mypage #72
  Admin/src/main/java/com/seveneleven/dto/MemberDto.java
  Admin/src/main/java/com/seveneleven/dto/MemberUpdate.java
  Admin/src/main/java/com/seveneleven/repository/DepartmentRepository.java
  Admin/src/main/java/com/seveneleven/repository/PositionRepository.java
  Admin/src/main/java/com/seveneleven/service/MemberMgmtService.java
  Admin/src/main/java/com/seveneleven/service/MemberMgmtServiceImpl.java
  Common/src/main/java/com/seveneleven/entity/member/Company.java
  Common/src/main/java/com/seveneleven/entity/member/Department.java
  Common/src/main/java/com/seveneleven/entity/member/Member.java
  Common/src/main/java/com/seveneleven/entity/member/Position.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/dto/MyPageGetMember.java
  Main/src/main/java/com/seveneleven/member/dto/PatchMember.java
  Main/src/main/java/com/seveneleven/member/repository/DepartmentRepository.java
  Main/src/main/java/com/seveneleven/member/repository/PositionRepository.java
  Main/src/main/java/com/seveneleven/member/service/MyPageServiceImpl.java
Labels: ✨ Feature

#90 Feature/member login #81
  .github/workflows/build_test.yml
  Admin/src/main/java/com/seveneleven/Main.java
  Admin/src/main/java/com/seveneleven/controller/AdminProjectController.java
  Admin/src/main/java/com/seveneleven/controller/CompanyController.java
  Admin/src/main/java/com/seveneleven/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/controller/MemberMgmtController.java
  Admin/src/main/java/com/seveneleven/service/CustomUserDetailsServiceImpl.java
  Admin/src/main/java/com/seveneleven/service/MemberMgmtService.java
  Admin/src/main/java/com/seveneleven/service/MemberMgmtServiceImpl.java
  Admin/src/main/resources/application.properties
  Common/build.gradle
  Common/src/main/java/com/seveneleven/Main.java
  Common/src/main/java/com/seveneleven/config/CustomUserDetailsService.java
  Common/src/main/java/com/seveneleven/config/JwtFilter.java
  Common/src/main/java/com/seveneleven/config/JwtSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/MailConfig.java
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/TokenProvider.java
  Common/src/main/java/com/seveneleven/config/annotation/AdminAuthorize.java
  Common/src/main/java/com/seveneleven/config/annotation/UserAuthorize.java
  Common/src/main/java/com/seveneleven/entity/member/Token.java
  Common/src/main/java/com/seveneleven/entity/member/constant/TokenStatus.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Common/src/main/java/com/seveneleven/util/security/CustomUserDetails.java
  Common/src/main/java/com/seveneleven/util/security/MemberDto.java
  Common/src/main/java/com/seveneleven/util/security/SHA256Util.java
  Common/src/main/java/com/seveneleven/util/security/SecurityUtil.java
  Common/src/main/java/com/seveneleven/util/security/TokenRepository.java
  Common/src/main/resources/application.properties
  Main/build.gradle
  Main/src/main/java/com/seveneleven/Main.java
  Main/src/main/java/com/seveneleven/member/controller/MemberController.java
  Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/dto/CheckMailPostRequest.java
  Main/src/main/java/com/seveneleven/member/dto/CompanyResponse.java
  Main/src/main/java/com/seveneleven/member/dto/LoginPost.java
  Main/src/main/java/com/seveneleven/member/dto/MemberDto.java
  Main/src/main/java/com/seveneleven/member/dto/MemberJoinDto.java
  Main/src/main/java/com/seveneleven/member/dto/MemberPatch.java
  Main/src/main/java/com/seveneleven/member/dto/SendMailPost.java
  Main/src/main/java/com/seveneleven/member/repository/CompanyRepository.java
  Main/src/main/java/com/seveneleven/member/repository/MemberRepository.java
  Main/src/main/java/com/seveneleven/member/service/CustomUserDetailsServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MailService.java
  Main/src/main/java/com/seveneleven/member/service/MailServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MemberService.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MyUserDetailsService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
  Main/src/main/resources/application.properties
Labels: ✨ Feature

#95 Feat: add swagger config
  Common/src/main/java/com/seveneleven/config/JwtAuthenticationEntryPoint.java
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/SwaggerConfiguration.java
Labels: ✨ Feature

#86 Refactor: 멀티 모듈로 분리 작업, 컨벤션 수정
  Admin/src/main/java/com/seveneleven/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Common/src/main/java/com/seveneleven/util/file/FileValidator.java
  Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
  Common/src/main/java/com/seveneleven/util/file/Service/S3ClientService.java
  Common/src/main/java/com/seveneleven/util/file/dto/FileMetadataDto.java
  Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
  Main/src/test/java/global/util/file/Service/FileServiceTest.java
Labels: 🔨 Refactor

#96 FEATURE/ 회원 프로필 이미지 등록/삭제/조회
  Admin/src/main/java/com/seveneleven/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
Labels: ✨ Feature

#101 Fix/post error
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🐞 Fix

#99 Feature/member login fix #98
  Admin/src/main/resources/application.properties
  Common/src/main/resources/application.properties
  Main/src/main/java/com/seveneleven/member/controller/MemberController.java
  Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
  Main/src/main/java/com/seveneleven/member/dto/LoginPost.java
  Main/src/main/java/com/seveneleven/member/dto/LoginResponse.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
  Main/src/main/resources/application.properties
Labels: ✨ Feature

#105 FEATURE: 게시물 관련 파일 기능 추가
  Admin/src/main/java/com/seveneleven/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
  Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
Labels: ✨ Feature

#109 Feat: 댓글 기능 구현 #97
  Common/src/main/java/com/seveneleven/entity/board/Comment.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/CommentController.java
  Main/src/main/java/com/seveneleven/board/controller/CommentDocs.java
  Main/src/main/java/com/seveneleven/board/dto/DeleteCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PatchCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
  Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#114 Feature/member cors
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
Labels: ✨ Feature

#110 Refactor/admin project#106
  Admin/src/main/java/com/seveneleven/application/adminProject/AdminProjectFacade.java
  Admin/src/main/java/com/seveneleven/application/adminProject/AdminProjectHistoryFacade.java
  Admin/src/main/java/com/seveneleven/common/CheckProjectValidity.java
  Admin/src/main/java/com/seveneleven/controller/AdminProjectController.java
  Admin/src/main/java/com/seveneleven/controller/AdminProjectDocs.java
  Admin/src/main/java/com/seveneleven/controller/CompanyController.java
  Admin/src/main/java/com/seveneleven/controller/CompanyDocs.java
  Admin/src/main/java/com/seveneleven/dto/GetCompanyDetail.java
  Admin/src/main/java/com/seveneleven/dto/GetProject.java
  Admin/src/main/java/com/seveneleven/dto/GetProjectHistory.java
  Admin/src/main/java/com/seveneleven/dto/PostProject.java
  Admin/src/main/java/com/seveneleven/dto/PutProject.java
  Admin/src/main/java/com/seveneleven/dto/ReadProjectHistory.java
  Admin/src/main/java/com/seveneleven/repository/AdminAdminMemberReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminCompanyReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectHistoryReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectHistoryStoreImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectRepository.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectStoreImpl.java
  Admin/src/main/java/com/seveneleven/repository/AdminProjectTypeReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/GetCompanyDetailResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/PostProjectRequestConverter.java
  Admin/src/main/java/com/seveneleven/repository/PostProjectResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/ProjectHistoryConverter.java
  Admin/src/main/java/com/seveneleven/repository/PutProjectResponseConverter.java
  Admin/src/main/java/com/seveneleven/service/AdminCompanyReader.java
  Admin/src/main/java/com/seveneleven/service/AdminCompanyService.java
  Admin/src/main/java/com/seveneleven/service/AdminMemberReader.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectHistoryReader.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectHistoryService.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectHistoryServiceImpl.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectHistoryStore.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectReader.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectService.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectServiceImpl.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectStore.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectTypeReader.java
  Common/src/main/java/com/seveneleven/entity/project/Project.java
  Common/src/main/java/com/seveneleven/entity/project/ProjectHistory.java
  Common/src/main/java/com/seveneleven/response/PaginatedResponse.java
Labels: 🔨 Refactor

#117 Feature/member cors
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/WebConfig.java
Labels: ✨ Feature

#121 Feature/member cors
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/WebConfig.java
Labels: ✨ Feature

#124 Feat: jwt filter 해제
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
Labels: ✨ Feature

#126 FEATURE: 게시물 링크 기능 구현, 파일기능 분리
  Common/src/main/java/com/seveneleven/config/OctetStreamReadMsgConverter.java
  Common/src/main/java/com/seveneleven/config/WebConfig.java
  Common/src/main/java/com/seveneleven/entity/file/FileMetadata.java
  Common/src/main/java/com/seveneleven/entity/file/FileMetadataHistory.java
  Common/src/main/java/com/seveneleven/entity/file/Link.java
  Common/src/main/java/com/seveneleven/entity/file/LinkHistory.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Common/src/main/java/com/seveneleven/util/file/Service/LinkService.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkInput.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkPayload.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkResponse.java
  Common/src/main/java/com/seveneleven/util/file/repository/LinkRepository.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#129 Refactor : first project refactor #127
  Common/src/main/java/com/seveneleven/entity/project/CheckRequest.java
  Common/src/main/java/com/seveneleven/entity/project/Project.java
  Common/src/main/java/com/seveneleven/util/security/CustomUserDetails.java
  Main/src/main/java/com/seveneleven/member/service/MemberService.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
  Main/src/main/java/com/seveneleven/project/controller/MyProjectController.java
  Main/src/main/java/com/seveneleven/project/controller/MyProjectDocs.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistDocs.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistFacade.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectStepController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectStepDocs.java
  Main/src/main/java/com/seveneleven/project/dto/DeleteProjectChecklist.java
  Main/src/main/java/com/seveneleven/project/dto/DeleteProjectStep.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectAuthorization.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectChecklistApplication.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectDetail.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectList.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectStep.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectAuthorization.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklist.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistReject.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectStep.java
  Main/src/main/java/com/seveneleven/project/dto/PutProjectChecklist.java
  Main/src/main/java/com/seveneleven/project/dto/PutProjectStep.java
  Main/src/main/java/com/seveneleven/project/repository/ProjectRepository.java
  Main/src/main/java/com/seveneleven/project/service/ProjectCheckRequestService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectCheckRequestServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/ProjectServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/ProjectStepService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectStepServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/ChecklistStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/dashboard/ProjectReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/step/StepReaderImpl.java
Labels: 🔨 Refactor

#130 update: 게시물 파일 업로드 분리
  Admin/src/main/resources/application.properties
  Common/src/main/java/com/seveneleven/util/file/FileValidator.java
  Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
  Common/src/main/java/com/seveneleven/util/file/Service/LinkService.java
  Common/src/main/java/com/seveneleven/util/file/Service/S3ClientService.java
  Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
  Common/src/main/resources/application.properties
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/resources/application.properties
Labels: 🔨 Refactor

#128 Feature/admin company#111
  Admin/src/main/java/com/seveneleven/application/adminCompany/AdminCompanyFacade.java
  Admin/src/main/java/com/seveneleven/application/adminProject/AdminProjectFacade.java
  Admin/src/main/java/com/seveneleven/controller/CompanyController.java
  Admin/src/main/java/com/seveneleven/dto/GetAllCompanies.java
  Admin/src/main/java/com/seveneleven/dto/GetCompanies.java
  Admin/src/main/java/com/seveneleven/dto/GetCompanyDetail.java
  Admin/src/main/java/com/seveneleven/dto/GetCompanyProject.java
  Admin/src/main/java/com/seveneleven/dto/GetProjectHistory.java
  Admin/src/main/java/com/seveneleven/dto/PostCompany.java
  Admin/src/main/java/com/seveneleven/dto/PutCompany.java
  Admin/src/main/java/com/seveneleven/repository/AdminCompanyReaderImpl.java
  Admin/src/main/java/com/seveneleven/repository/GetAllCompaniesConverter.java
  Admin/src/main/java/com/seveneleven/repository/GetCompaniesResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/GetCompanyProjectResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/PostCompanyRequestConverter.java
  Admin/src/main/java/com/seveneleven/repository/PostCompanyResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/ProjectResponseConverter.java
  Admin/src/main/java/com/seveneleven/repository/PutCompanyRequestConverter.java
  Admin/src/main/java/com/seveneleven/repository/PutCompanyResponseConverter.java
  Admin/src/main/java/com/seveneleven/service/AdminCompanyReader.java
  Admin/src/main/java/com/seveneleven/service/AdminCompanyService.java
  Admin/src/main/java/com/seveneleven/service/AdminCompanyServiceImpl.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectService.java
  Admin/src/main/java/com/seveneleven/service/AdminProjectServiceImpl.java
Labels: 🔨 Refactor

#137 Setting : 액추에이터, 프로메테우스 의존성 설정 추가
  Admin/build.gradle
  Admin/src/main/resources/application.properties
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Main/build.gradle
  Main/src/main/resources/application.properties
Labels: ⚙ Setting

#139 refactor : bnsManagerName -> name 제거, customerName -> customerCompany…
  Admin/src/main/java/com/seveneleven/dto/GetCompanyProject.java
  Admin/src/main/java/com/seveneleven/dto/GetProject.java
  Admin/src/main/java/com/seveneleven/dto/GetProjectHistory.java
  Admin/src/main/java/com/seveneleven/dto/PostProject.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectDetail.java
Labels: 🔨 Refactor
