Repository Kernel360/KDEV3_DevLens_BE, pull requests merged in 2025-02, with the labels that each got.

#116 feat : log config
  .gitignore
  Admin/src/main/resources/application.properties
  Common/src/main/java/com/seveneleven/config/AuthenticationEventListener.java
  Common/src/main/java/com/seveneleven/config/JwtFilter.java
  Common/src/main/java/com/seveneleven/config/LogbackConfig.java
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/config/aop/ControllerAop.java
  Common/src/main/java/com/seveneleven/config/aop/ServiceAop.java
  Common/src/main/java/com/seveneleven/util/GetIpUtil.java
  Common/src/main/resources/application.properties
  Main/src/main/java/com/seveneleven/project/dto/GetProjectDetail.java
  Main/src/main/resources/application.properties
  build.gradle
Labels: ✨ Feature

#140 feat: 체크요청/반려 파일 기능 초안
  Common/src/main/java/com/seveneleven/util/file/Service/FileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistDocs.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReader.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStoreImpl.java
Labels: ✨ Feature

#145 Feature/admin member update #142
  Admin/src/main/java/com/seveneleven/controller/MemberMgmtController.java
  Common/src/main/java/com/seveneleven/config/TokenProvider.java
  Common/src/main/java/com/seveneleven/config/WebConfig.java
  Main/src/main/java/com/seveneleven/member/controller/MemberController.java
Labels: ✨ Feature

#158 feat: 게시글 및 댓글의 dto 수정
  Common/src/main/java/com/seveneleven/entity/board/Comment.java
  Common/src/main/java/com/seveneleven/entity/board/Post.java
  Common/src/main/java/com/seveneleven/entity/board/PostHistory.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/controller/CommentController.java
  Main/src/main/java/com/seveneleven/board/controller/CommentDocs.java
  Main/src/main/java/com/seveneleven/board/dto/DeleteCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PatchCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostCommentRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#176 feat: 게시글 및 댓글 AuthenticationPrincipal 추가 및 AutditorAwareImpl 수정
  Common/src/main/java/com/seveneleven/config/AuditorAwareImpl.java
  Common/src/main/java/com/seveneleven/config/TokenProvider.java
  Common/src/main/java/com/seveneleven/util/security/dto/CustomUserDetails.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/controller/CommentController.java
  Main/src/main/java/com/seveneleven/board/controller/CommentDocs.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
Labels: ✨ Feature

#179 Feat : 회원 리팩토링 및 이력, 로그 추가
  Admin/src/main/java/com/seveneleven/controller/AdminMemberController.java
  Admin/src/main/java/com/seveneleven/controller/AdminMemberDocs.java
  Admin/src/main/java/com/seveneleven/repository/PasswordHistoryRepository.java
  Admin/src/main/java/com/seveneleven/repository/ProfileHistoryRepository.java
  Admin/src/main/java/com/seveneleven/service/AdminMemberService.java
  Admin/src/main/java/com/seveneleven/service/AdminMemberServiceImpl.java
  Common/src/main/java/com/seveneleven/config/TokenProvider.java
  Common/src/main/java/com/seveneleven/entity/member/MemberProfileHistory.java
  Common/src/main/java/com/seveneleven/util/security/repository/RefreshTokenRepository.java
  Common/src/main/java/com/seveneleven/util/security/service/RefreshTokenServiceImpl.java
  Main/src/main/java/com/seveneleven/member/controller/MemberController.java
  Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
  Main/src/main/java/com/seveneleven/member/repository/PasswordHistoryRepository.java
  Main/src/main/java/com/seveneleven/member/repository/ProfileHistoryRepository.java
  Main/src/main/java/com/seveneleven/member/service/MemberService.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MyPageServiceImpl.java
Labels: 🔨 Refactor

#160 Feat : 프로젝트 체크리스트 링크 기능 구현 및 파일 기능 수정
  Common/src/main/java/com/seveneleven/config/SwaggerConfiguration.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkInput.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkPayload.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistApplication.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectChecklistReject.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkReader.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
Labels: ✨ Feature

#188 Feat: 회원 로직 수정 및 로그 추가
  Admin/src/main/java/com/seveneleven/member/controller/AdminAuthController.java
  Admin/src/main/java/com/seveneleven/member/controller/AdminAuthDocs.java
  Admin/src/main/java/com/seveneleven/member/dto/MemberDto.java
  Admin/src/main/java/com/seveneleven/member/repository/AdminMemberRepository.java
  Admin/src/main/java/com/seveneleven/member/service/AdminMemberServiceImpl.java
  Common/src/main/java/com/seveneleven/config/JwtFilter.java
  Common/src/main/java/com/seveneleven/config/SpringSecurityConfig.java
  Common/src/main/java/com/seveneleven/util/security/service/RefreshTokenServiceImpl.java
  Main/src/main/java/com/seveneleven/member/controller/AuthController.java
  Main/src/main/java/com/seveneleven/member/controller/AuthDocs.java
  Main/src/main/java/com/seveneleven/member/controller/MemberDocs.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
Labels: ✨ Feature

#194 refactor: 게시글 리팩토링
  Common/src/main/java/com/seveneleven/entity/board/Post.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostReader.java
  Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostStore.java
  Main/src/main/java/com/seveneleven/board/service/PostStoreImpl.java
Labels: 🔨 Refactor

#197 Feature/admin fix#185
  Admin/src/main/java/com/seveneleven/common/AdminExceptionHandler.java
  Admin/src/main/java/com/seveneleven/company/application/AdminCompanyFacade.java
  Admin/src/main/java/com/seveneleven/company/controller/CompanyController.java
  Admin/src/main/java/com/seveneleven/company/controller/CompanyDocs.java
  Admin/src/main/java/com/seveneleven/company/dto/PostCompany.java
  Admin/src/main/java/com/seveneleven/company/dto/PutCompany.java
  Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyHistoryRepository.java
  Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyHistoryStoreImpl.java
  Admin/src/main/java/com/seveneleven/company/repository/AdminCompanyReaderImpl.java
  Admin/src/main/java/com/seveneleven/company/repository/CompanyRepository.java
  Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryService.java
  Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryServiceImpl.java
  Admin/src/main/java/com/seveneleven/company/service/AdminCompanyHistoryStore.java
  Admin/src/main/java/com/seveneleven/company/service/AdminCompanyService.java
  Admin/src/main/java/com/seveneleven/company/service/AdminCompanyServiceImpl.java
  Admin/src/main/java/com/seveneleven/member/repository/AdminMemberRepository.java
  Admin/src/main/java/com/seveneleven/member/service/AdminMemberService.java
  Admin/src/main/java/com/seveneleven/member/service/AdminMemberServiceImpl.java
  Admin/src/main/java/com/seveneleven/project/controller/AdminProjectController.java
  Admin/src/main/java/com/seveneleven/project/controller/AdminProjectDocs.java
  Admin/src/main/java/com/seveneleven/project/dto/PostProject.java
  Admin/src/main/java/com/seveneleven/project/dto/PutProject.java
  Common/src/main/java/com/seveneleven/entity/member/Company.java
  Common/src/main/java/com/seveneleven/entity/member/CompanyHistory.java
Labels: ✨ Feature

#187 Feat: 파일 관련 AuthenticationPrincipal 추가
  Admin/src/main/java/com/seveneleven/company/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/util/file/handler/FileHandler.java
  Common/src/main/java/com/seveneleven/util/file/handler/LinkHandler.java
  Common/src/main/java/com/seveneleven/util/file/handler/S3ClientHandler.java
  Common/src/main/java/com/seveneleven/util/security/dto/CustomUserDetails.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
Labels: ✨ Feature, 🔨 Refactor

#201 Setting: CORS 추가
  Common/src/main/java/com/seveneleven/config/WebConfig.java
Labels: ⚙ Setting

#196 Feat : 프로젝트 접근 권한 수정 #191
  Admin/src/main/java/com/seveneleven/project/application/AdminProjectFacade.java
  Common/src/main/java/com/seveneleven/entity/project/MemberProjectStepId.java
  Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorization.java
  Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorizationHistory.java
  Common/src/main/java/com/seveneleven/util/security/service/ProjectAuthorizationCheckService.java
  Common/src/main/java/com/seveneleven/util/security/service/ProjectAuthorizationCheckServiceImpl.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationDocs.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationFacade.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectStepController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectStepDocs.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectStepFacade.java
  Main/src/main/java/com/seveneleven/project/dto/GetMemberAuthorization.java
  Main/src/main/java/com/seveneleven/project/dto/GetProjectAuthorization.java
  Main/src/main/java/com/seveneleven/project/dto/PostProjectAuthorization.java
  Main/src/main/java/com/seveneleven/project/repository/ProjectAuthorizationRepository.java
  Main/src/main/java/com/seveneleven/project/repository/ProjectRepository.java
  Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReader.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReaderImpl.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationStore.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationStoreImpl.java
Labels: ✨ Feature

#209 Feat: 파일 이력 등록 추가
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileHistoryService.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/entity/file/FileMetadataHistory.java
  Common/src/main/java/com/seveneleven/util/file/handler/FileHandler.java
  Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataHistoryRepository.java
  Main/src/main/java/com/seveneleven/board/service/PostFileHistoryService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileHistoryService.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileHistoryStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileHistoryStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileStoreImpl.java
Labels: ✨ Feature

#210 Feat: 회원 기능 수정 및 추가
  Common/src/main/java/com/seveneleven/config/JwtFilter.java
  Common/src/main/java/com/seveneleven/config/TokenProvider.java
  Common/src/main/java/com/seveneleven/entity/member/RefreshToken.java
  Common/src/main/java/com/seveneleven/util/security/repository/RefreshTokenRepository.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
Labels: ✨ Feature

#203 Feature/project authorization refactor 2 #191
  Admin/src/main/java/com/seveneleven/company/application/AdminCompanyFacade.java
  Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorization.java
  Common/src/main/java/com/seveneleven/entity/project/ProjectAuthorizationHistory.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationController.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationDocs.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectAuthorizationFacade.java
  Main/src/main/java/com/seveneleven/project/dto/GetMemberAuthorization.java
  Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectAuthorizationServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReader.java
  Main/src/main/java/com/seveneleven/project/service/authorization/AuthorizationReaderImpl.java
Labels: 🔨 Refactor

#215 setting: cors 수정
  Admin/src/main/java/com/seveneleven/AdminApplication.java
  Common/src/main/java/com/seveneleven/config/WebConfig.java
  Main/src/main/java/com/seveneleven/MainApplication.java
Labels: ⚙ Setting

#220 Feat: 링크 이력 기능
  Common/src/main/java/com/seveneleven/entity/file/LinkHistory.java
  Common/src/main/java/com/seveneleven/util/file/handler/FileHandler.java
  Common/src/main/java/com/seveneleven/util/file/handler/LinkHandler.java
  Common/src/main/java/com/seveneleven/util/file/repository/LinkHistoryRepository.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkHistoryService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkHistoryStore.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestLinkHistoryStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestStoreImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckResultStoreImpl.java
Labels: ✨ Feature

#221 Refactor: comment refactor
  Common/src/main/java/com/seveneleven/entity/board/Comment.java
  Common/src/main/java/com/seveneleven/entity/board/CommentHistory.java
  Common/src/main/java/com/seveneleven/entity/board/PostHistory.java
  Common/src/main/java/com/seveneleven/entity/board/constant/HistoryAction.java
  Common/src/main/java/com/seveneleven/response/ErrorCode.java
  Common/src/main/java/com/seveneleven/util/security/dto/CustomUserDetails.java
  Common/src/main/java/com/seveneleven/util/security/dto/MemberDto.java
  Main/src/main/java/com/seveneleven/board/controller/CommentController.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
  Main/src/main/java/com/seveneleven/board/repository/CommentHistoryRepository.java
  Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
  Main/src/main/java/com/seveneleven/board/service/CommentReader.java
  Main/src/main/java/com/seveneleven/board/service/CommentReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/CommentStore.java
  Main/src/main/java/com/seveneleven/board/service/CommentStoreImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostReader.java
  Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostStore.java
  Main/src/main/java/com/seveneleven/board/service/PostStoreImpl.java
Labels: 🔨 Refactor

#226 Refactor: 파일 반환 dto optional로 변경
  Admin/src/main/java/com/seveneleven/company/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
  Common/src/main/java/com/seveneleven/entity/file/Link.java
  Common/src/main/java/com/seveneleven/entity/file/LinkHistory.java
  Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
  Common/src/main/java/com/seveneleven/util/file/dto/FileMetadataDto.java
  Common/src/main/java/com/seveneleven/util/file/dto/FileMetadataResponse.java
  Common/src/main/java/com/seveneleven/util/file/dto/LinkInput.java
  Common/src/main/resources/application.properties
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
  Main/src/main/java/com/seveneleven/member/service/MyPageServiceImpl.java
  Main/src/main/java/com/seveneleven/project/controller/ProjectChecklistController.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistService.java
  Main/src/main/java/com/seveneleven/project/service/ProjectChecklistServiceImpl.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReader.java
  Main/src/main/java/com/seveneleven/project/service/checklist/CheckRequestFileReaderImpl.java
Labels: 🔨 Refactor

#231 Update/ 단일 이미지 업로드 로직 변경
  Admin/src/main/java/com/seveneleven/company/controller/CompanyFileController.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
Labels: 🔨 Refactor

#236 Update: 게시물 생성시 반환값 추가
  Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🔨 Refactor

#237 Update: 게시물 상세 링크, 파일 반환 추가
  Common/src/main/java/com/seveneleven/exception/GlobalExceptionHandler.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🔨 Refactor

#242 Fix: Delete Post Link History 파라미터 수정
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🐞 Fix

#244 feat: 전체 게시물 조회 기능 추가
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/dto/PostListResponse.java
  Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
  Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
  Main/src/main/java/com/seveneleven/board/service/PostReader.java
  Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/project/repository/ProjectStepRepository.java
Labels: ✨ Feature

#243 Refactor/service seperation
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileHistoryService.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileHistoryServiceImpl.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileService.java
  Admin/src/main/java/com/seveneleven/company/service/CompanyFileServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostFileHistoryService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileHistoryServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkHistoryService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkHistoryServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileHistoryService.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileHistoryServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileService.java
  Main/src/main/java/com/seveneleven/member/service/MemberFileServiceImpl.java
Labels: 🔨 Refactor

#249 Update: 게시물 파일/링크 업데이트 로직 변경
  Common/src/main/java/com/seveneleven/entity/file/constant/FileCategory.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/dto/PostCreateRequest.java
  Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🔨 Refactor

#250 Feature : 게시글 및 댓글 작성자 확인 기능 수정
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/controller/BoardDocs.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
  Main/src/main/java/com/seveneleven/board/service/CommentReader.java
  Main/src/main/java/com/seveneleven/board/service/CommentReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#251 Chore: 파일/링크 수정 롤백
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/dto/PostUpdateRequest.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🔨 Refactor

#256 feat: 게시글 권한(작성자, 관리자) 수정
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#262 chore: modify file upload return value
  Common/src/main/java/com/seveneleven/util/file/dto/FileMetadataResponse.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
Labels: 🔨 Refactor

#263 Chore: modify link upload return
  Common/src/main/java/com/seveneleven/util/file/dto/LinkResponse.java
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkServiceImpl.java
Labels: 🔨 Refactor

#264 fix: logback file name
  Admin/src/main/resources/logback.xml
  Main/src/main/resources/logback.xml
Labels: 🐞 Fix

#269 feat: 게시글 상세 조회시 원글 및 답글 필드 추가
  Common/src/main/java/com/seveneleven/entity/board/Post.java
  Common/src/main/java/com/seveneleven/entity/board/constant/PostFilter.java
  Main/src/main/java/com/seveneleven/board/dto/PostListResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/dto/RelatedPostResponse.java
  Main/src/main/java/com/seveneleven/board/repository/PostRepository.java
  Main/src/main/java/com/seveneleven/board/service/PostReader.java
  Main/src/main/java/com/seveneleven/board/service/PostReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#272 fix: 게시글 상세 조회 시 원글 및 답글 구분 에러 수정
  Common/src/main/java/com/seveneleven/entity/board/Post.java
Labels: 🐞 Fix

#273 fix: 게시글 상세 조회 api에 log 추가
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🐞 Fix

#274 fix: 게시글 상세 조회 시 500 에러 해결
  Common/src/main/java/com/seveneleven/entity/board/Post.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: 🐞 Fix

#284 Feat: 프로필 사진, 게시물 파일 권한 추가
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostFileService.java
  Main/src/main/java/com/seveneleven/board/service/PostFileServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/member/controller/MyPageController.java
Labels: ✨ Feature

#283 Docs: Readme 작성
  README.md
  src/resources/logo.png
  src/resources/project-architecture.png
  src/resources/skill/Discord.png
  src/resources/skill/Docker.png
  src/resources/skill/GCP.png
  src/resources/skill/Github.png
  src/resources/skill/JWT.png
  src/resources/skill/Java.png
  src/resources/skill/Jenkins.png
  src/resources/skill/Mysql.png
  src/resources/skill/Nginx.png
  src/resources/skill/Notion.png
  src/resources/skill/Redis.png
  src/resources/skill/SpringBoot.png
  src/resources/skill/SpringDataJPA.png
  src/resources/skill/SpringSecurity.png
  src/resources/skill/Swagger.png
  src/resources/화면1.png
  src/resources/화면2.png
  src/resources/화면3.png
  src/resources/화면4.png
Labels: 📃 Docs

#285 Feat: 게시물 링크 api 권한 추가
  Main/src/main/java/com/seveneleven/board/controller/BoardController.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkService.java
  Main/src/main/java/com/seveneleven/board/service/PostLinkServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostService.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
Labels: ✨ Feature

#290 Feat: 게시물, 댓글 작성자 프로필 이미지 추가
  Common/src/main/java/com/seveneleven/util/file/repository/FileMetadataRepository.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentDetailResponse.java
  Main/src/main/java/com/seveneleven/board/dto/GetCommentResponse.java
  Main/src/main/java/com/seveneleven/board/dto/PostResponse.java
  Main/src/main/java/com/seveneleven/board/service/CommentService.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/board/service/PostServiceImpl.java
  Main/src/main/java/com/seveneleven/member/service/MemberService.java
  Main/src/main/java/com/seveneleven/member/service/MemberServiceImpl.java
Labels: ✨ Feature

#293 Feature: notification comment #292
  Main/src/main/java/com/seveneleven/board/repository/CommentRepository.java
  Main/src/main/java/com/seveneleven/board/service/CommentReader.java
  Main/src/main/java/com/seveneleven/board/service/CommentReaderImpl.java
  Main/src/main/java/com/seveneleven/board/service/CommentServiceImpl.java
  Main/src/main/java/com/seveneleven/notification/controller/NotificationController.java
  Main/src/main/java/com/seveneleven/notification/service/NotificationService.java
Labels: ✨ Feature

#312 Update: 25/02/20 13:16 브랜치 최신화
  Main/src/main/java/com/seveneleven/project/service/ProjectStepServiceImpl.java
Labels: 🌏 Deploy
